name: Build using yarn

on:
    push:
        branches: ['**']
    workflow_dispatch:

jobs:
    build:
        name: Build on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'

            - name: Enable corepack
              run: corepack enable

            - name: Update yarn version
              run: yarn set version berry

            - name: Install dependencies
              run: yarn install

            - name: Build project
              run: yarn build
